E-learning/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

E-learning/force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

E-learning/force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <label>Module Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

E-learning/force-app/main/default/objects/Module_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

E-learning/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

E-learning/force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <label>Question Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

E-learning/force-app/main/default/objects/Question_Response__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

E-learning/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

E-learning/force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <label>Unit Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

E-learning/force-app/main/default/objects/Unit_Response__c/fields/Numbers_of_tries__c.field-meta.xml
<CustomField>
    <fullName>Numbers_of_tries__c</fullName>
    <label>Numbers of tries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

E-learning/force-app/main/default/objects/Unit_Response__c/fields/unit_Status__c.field-meta.xml
<CustomField>
    <fullName>unit_Status__c</fullName>
    <label>unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

E-learning/force-app/main/default/objects/Unit_Response__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Unit Responses</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

E-learning/force-app/main/default/classes/UnitService.cls
public class UnitService {

    
    public static Boolean registerUnitResponse(Id unitId, String jsonAnswer){

        SavePoint sp = Database.setSavepoint();
        try{
            
       
        //Busco la unidad desde la base de datos.
        Unit__c unit = [SELECT Module__c,(SELECT Id, Numbers_of_Tries__C FROM Unit_Responses__r WHERE Module_Response__C.User__c =: Userinfo.getUserId() ORDER BY Numbers_of_Tries__C DESC LIMIT 1 ), (SELECT id, name FROM Questions__r) from Unit__c where Id =: unitId];
        
        //Verifico si existe un modulo
        Module_Response__c moduleResp = [SELECT Id from Module_Response__c WHERE Module__C =: Unit.Module__C AND User__c =: Userinfo.getUserId() AND Status__c =: 'In Progress'];
    
            if( moduleResp == null){
            //Creación e inserción de Module Response.
            moduleResp = new Module_Response__c (User__c= Userinfo.getUserId(), Module__c = unit.Module__C, Status__c = 'In Progress' );
            insert moduleResp;
        }

               //Creacion e insercion de unit response
               Unit_Response__c unitResp = new Unit_Response__c(Unit__c = unitId, Module_Response__c = moduleResp.Id, unit_Status__c = 'Draft');
               //NTH!
               unitResp.Numbers_of_tries__c = !unit.Unit_Responses__r.isEmpty() ? unit.Unit_Responses__r[0].Numbers_Of_Tries__c + 1 : 1;
               insert unitResp;

               
        //Creo y cargo question responses
        Map<Id,Id> answerMap = (Map<Id,Id>)JSON.deserializeStrict(jsonAnswer, Map<Id,Id>.class);
        List<Question_Response__c> questionRespList = new List<Question_Response__c>();
        for(Question__c question : unit.Questions__r){
            //Verifico si la pregunta fue respondida en el mapa
            if(answerMap.containsKey(question.Id)){
                Question_Response__c questionResp = new Question_Response__c(Question__c = question.Id, Unit_Response__c = unitResp.Id, Answer__c = answerMap.get(question.Id));
                questionRespList.add(questionResp);
            }else{
                throw new Exception('La pregunta ' + question.Name + ' no fue respondida y es requerida.');
            }
        }
        insert questionRespList;
        unitResp.unit_Status__c = 'Answered';
        update unitResp;
        return true;
    }catch(Exception e){
        Database.rollback(sp);
        return false;
        throw e;
    }
   }
}